services:
  nginx:
    image: nginx:1.29.0
    container_name: carekobooks-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - carekonet-cloudflared
      - carekonet-nginx
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: carekobooks-cloudflared
    environment:
      TZ: America/Sao_Paulo
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      - carekonet-cloudflared
    restart: unless-stopped

networks:
  carekonet-cloudflared:
  carekonet-nginx:
    external: true
